import type { Metadata } from "next";
import "./globals.css";
import { Comfortaa } from '@next/font/google';

const comfortaa = Comfortaa({
  weight: ['300', '400', '500', '600', '700'], // Você pode escolher os pesos disponíveis
  subsets: ['latin'], // Escolha o subset
  variable: '--font-comfortaa', // Defina uma variável CSS
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${comfortaa.variable} font-sans antialiased`}>
        {children}
      </body>
    </html>
  );
}
